name: Secret Leak Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  secret_scan:
    name: secret-scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning (Gitleaks Docker)
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            ghcr.io/gitleaks/gitleaks:v8.28.0@sha256:cdbb7c955abce02001a9f6c9f602fb195b7fadc1e812065883f695d1eeaba854 \
            git --verbose --log-opts="--all" --gitleaks-ignore-path=/repo/.gitleaksignore /repo
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@4d2a8ef686341ee81a283d1d0fbcb97a5017ef35
        with:
          base: ""
          head: HEAD
          extra_args: --results=verified,unknown
